CompileTimeCalibanClientPlugin: couple of sbt plugins allowing, at compile time, to generate Caliban client code from Caliban GraphQL server code (#1037)
* [POC] sbt plugins allowing, at compile time, to generate Caliban client code from Caliban `GraphQL` server code

* [POC] Second design that fixes the compilation ordering problem

* Add cache and fix doc

* Clean

* Clean

* Fix scaladoc

* Init tests

* Fix tests

* Fix tests

* Composition > inheritance

* Pass caliban settings to the generator

* Clean

* Update tests

* Review: Clean

* Review: Simplify code

* Review: Simplify test project

* Review: Simplify test project

* Fix tests

* Review: Remove useless zio dependency

* Fix tests

* Pass settings in the generator instead of via sbt

* Fix tests

* Clean code

* Clean

* Add tests for the default values

* Clean

* Fix tests

* Review: Fix Windows compatibility

* WIP: It compiles

* toto

* WIP: Simplify

* WIP: Speedup build

* WIP: Clean

* WIP: Devon Stewart idea POC

* WIP: Implement Devon Stewart idea

* Make tests pass again

* Clean

* Fix setting name

* Fix tests

* Accept more than one API ref

* Accept more than one client settings

* Fix tests

* Clean

* Move the generators settings to the server side

* Fix tests

* Remove the generators once everything is generated to not pollute the run command

* Factorize cache code

* When server settings change, clients should be re-generated

* `clientName` is not mandatory

* Clean

* Clean code

* Improve and speed up tests

* Fix tests

* Implement a more complex project for tests with 2 servers

* Fix tests

* Trigger CI

* Implement a safe `writeFile` function

* Fix tests

* Prefer `sbt.IO` file manipulation functions over `java.nio.file.Files` racy ones

* Trigger CI

* Try( Fix downloading issue )

* Update sbt

* Fix `java.lang.IllegalArgumentException: character to be escaped is missing` bug on Windows

* Wrap blocking operation in `effectBlocking` && Use an "atomic write" strategy

* Clean

* Add tests: Prove that the `run` command is not polluted by the generated generators in the servers

* Rollback to sbt 1.5.4

* Plan test suite

* Try { Fix error:

```
[info] compiling 23 Scala sources to /home/runner/work/poc_compile_time_caliban_client_generation/poc_compile_time_caliban_client_generation/modules/caliban-clients/target/scala-2.12/classes ...
[error] IO error while decoding /home/runner/work/poc_compile_time_caliban_client_generation/poc_compile_time_caliban_client_generation/modules/caliban-clients/src/main/scala/poc/caliban/client/generated/posts/splitted with UTF-8: /home/runner/work/poc_compile_time_caliban_client_generation/poc_compile_time_caliban_client_generation/modules/caliban-clients/src/main/scala/poc/caliban/client/generated/posts/splitted (Is a directory)
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (caliban-clients / Compile / compileIncremental) Compilation failed
```

}

* Trigger CI

* Add tests: Prove that the server generated classes are not uselessly re-generated all the time

* Add tests:
 - Prove that the server generated classes are not uselessly re-generated all the time
 - Prove that the client generated classes are not uselessly re-generated all the time

* Fix POC CI

* Add tests: When server settings are modified, the server and the client classes are re-generated.

And fix code. The waiting mechanism was dead lockign when only one server config was changed, waiting forever for the other server 'metadata' file.

* Finish sbt scripted tests

* Write internal plugin doc

* Implement unit tests

* Fix doc and scripted tests

* Clean PR

* Clean

* Add unit test

* Try( Fix errors:

```scala
[error] Caused by: coursierapi.error.DownloadingArtifactsError: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/1.0.3/scala-parallel-collections_2.13-1.0.3.jar: checksum not found: /home/circleci/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/1.0.3/scala-parallel-collections_2.13-1.0.3.jar
```

)

* Try( Fix errors:

```scala
[error] Caused by: coursierapi.error.DownloadingArtifactsError: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/1.0.3/scala-parallel-collections_2.13-1.0.3.jar: checksum not found: /home/circleci/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/1.0.3/scala-parallel-collections_2.13-1.0.3.jar
```

)

* Simplify code

* Try

* Fix compilation

* Add some debug

* Trigger CI

* Update scala 2.12

* Fix tests

* Update sbt

* Update scalafmt

* Trigger CI

* Trigger CI

* Trigger CI

* Trigger CI

* Remove `.withRespectVersion(false)`

* Use a default version

* Use a default version, BIS

* Use a default version, TER

* Rollback to sbt 1.5.4 because of https://github.com/sbt/sbt/issues/6648#issuecomment-912696923

* Add comment

* Remove prelude

* Remove `Resolver.mavenLocal`

* Put back the `.scalafmt.conf`. Should work now.

* Clean

* Add debug

* Ensure parameters order in generated code is deterministic

* Update Scala 2.12

* Update scalafmt libs

* Clean

* Try( Fix scalfmt download issue )

* Try( Fix scalfmt download issue )

* Fix tests

* Clean code

* Debug sbt as advised here: https://github.com/sbt/sbt/issues/6655#issuecomment-918860847

* Fix bugs:
 - https://github.com/sbt/sbt/issues/6655
 - https://github.com/scala/scala/pull/9757

* Clean PR

* Clean PR

* Clean PR

* Fail with an error

* Fail with an error

* Clean PR

* Clean PR

* Clean PR

* Simplify documentation as asked in review

* Clean PR

* Clean PR

Co-authored-by: Pierre Ricadat <pierre.ricadat@devsisters.com>